import { useState } from "react";

import { DraftNote, GenerationResponse, NoteDefinition } from "@/models";
import { ApplicationError } from "@/utility/errors";
import { webApiAction } from "@/utility/web-api";

import { useAbortSignal } from "./use-abort-signal";
import { useAccessToken } from "./use-access-token";

type NoteGeneratorProps = {
  onGenerating?: () => void;
  onGenerated: (draftNote: DraftNote) => void;
  onError: (error: ApplicationError, retry: () => void) => void;
};

export function useNoteGenerator({
  onGenerating,
  onGenerated,
  onError,
}: NoteGeneratorProps) {
  const accessToken = useAccessToken();
  const { signal, abortController } = useAbortSignal();
  const [generatingNoteType, setGeneratingNoteType] =
    useState<NoteDefinition>();

  const generateNote = async (
    noteType: NoteDefinition,
    transcript: string,
    includeFooter: boolean = true,
  ) => {
    if (generatingNoteType) {
      abortController.abort();
    }

    onGenerating?.();
    setGeneratingNoteType(noteType);

    const abortSignal = signal.current;

    try {
      const requestData = {
        instructions: noteType.instructions,
        transcript: transcript,
      };

      const response = await webApiAction<GenerationResponse>(
        "POST",
        "/api/tasks/generate-draft-note",
        {
          data: requestData,
          accessToken: accessToken,
          abortSignal: abortSignal,
        },
      );

      const draftNote: DraftNote = {
        tag: response.tag,
        noteDefinitionUuid: noteType.uuid,
        createdAt: new Date(),
        title: noteType.title,
        text: response.text,
        generationService: "Snowflake Cortex",
        model: "",
        timeToGenerate: 0,
        isDiscarded: false,
        isUnsaved: true,
      };

      if (includeFooter) {
        draftNote.text += `\n\n<<This note, in part generated by the AHS Jenkins Scribe, is approved for the medical record. Note ID: ${draftNote.tag}. The patient verbally consented to using this tool.>>`;
      }

      onGenerated(draftNote);
    } catch (e: unknown) {
      onError(e as ApplicationError, () => generateNote(noteType, transcript));
    } finally {
      setGeneratingNoteType(undefined);
    }
  };

  const abort = () => {
    abortController.abort();
    setGeneratingNoteType(undefined);
  };

  return { generateNote, abort, generatingNoteType } as const;
}
