import { useState } from "react";

import { DraftNote } from "@/core/types";
import { useWebApi } from "@/services/web-api/use-web-api";
import { ApplicationError } from "@/utility/errors";
import { useAbortController } from "@/utility/use-abort-controller";

import { createNote, ValidNoteType } from "./create-note";

type NoteGeneratorProps = {
  onGenerating?: () => void;
  onGenerated: (draftNote: DraftNote) => void;
  onError: (error: ApplicationError, retry: () => void) => void;
};

export function useNoteGenerator({
  onGenerating,
  onGenerated,
  onError,
}: NoteGeneratorProps) {
  const webApi = useWebApi();
  const controller = useAbortController();
  const [generatingNoteType, setGeneratingNoteType] = useState<ValidNoteType>();

  const generateNote = async (
    noteType: ValidNoteType,
    transcript: string,
    includeFooter: boolean = true,
  ) => {
    if (generatingNoteType) {
      controller.abort();
    }

    onGenerating?.();
    setGeneratingNoteType(noteType);

    const abortSignal = controller.signal.current;

    try {
      const response = await webApi.tasks.generateDraftNote(
        noteType.instructions,
        transcript,
        abortSignal,
      );

      const draftNote: DraftNote = createNote({
        noteType: noteType,
        tag: response.tag,
        text: response.text,
      });

      if (includeFooter) {
        const noteFooter = `<<This note, in part generated by the AHS Jenkins Scribe, is approved for the medical record. Note ID: ${draftNote.tag}. The patient verbally consented to using this tool.>>`;

        draftNote.text += `\n\n${noteFooter}`;
      }

      onGenerated(draftNote);
    } catch (e: unknown) {
      onError(e as ApplicationError, () => generateNote(noteType, transcript));
    } finally {
      setGeneratingNoteType(undefined);
    }
  };

  const abort = () => {
    if (generatingNoteType) {
      controller.abort();
      setGeneratingNoteType(undefined);
    }
  };

  return { generateNote, abort, generatingNoteType } as const;
}
