import { useState } from "react";

import { useAccessToken } from "@/services/session-management/use-access-token";
import { httpAction } from "@/services/web-api/base-queries";
import { ApplicationError } from "@/utility/errors";
import { useAbortController } from "@/utility/use-abort-controller";

import { NoteDefinition } from "@/features/note-types/note-definition";

import { DraftNote } from "./draft-note";

export type NoteGeneratorOutput = {
  text: string;
  tag: string;
};

type NoteGeneratorProps = {
  onGenerating?: () => void;
  onGenerated: (draftNote: DraftNote) => void;
  onError: (error: ApplicationError, retry: () => void) => void;
};

export function useNoteGenerator({
  onGenerating,
  onGenerated,
  onError,
}: NoteGeneratorProps) {
  const { accessToken } = useAccessToken();
  const controller = useAbortController();
  const [generatingNoteType, setGeneratingNoteType] =
    useState<NoteDefinition>();

  const generateNote = async (
    noteType: NoteDefinition,
    transcript: string,
    includeFooter: boolean = true,
  ) => {
    if (generatingNoteType) {
      controller.abort();
    }

    onGenerating?.();
    setGeneratingNoteType(noteType);

    const abortSignal = controller.signal.current;

    try {
      const requestData = {
        instructions: noteType.instructions,
        transcript: transcript,
      };

      const response = await httpAction<NoteGeneratorOutput>(
        "POST",
        "/api/tasks/generate-draft-note",
        {
          data: requestData,
          accessToken: accessToken,
          signal: abortSignal,
        },
      );

      const draftNote: DraftNote = {
        tag: response.tag,
        noteDefinitionUuid: noteType.uuid,
        createdAt: new Date(),
        title: noteType.title,
        text: response.text,
        generationService: "Snowflake Cortex",
        model: "",
        timeToGenerate: 0,
        isDiscarded: false,
        isUnsaved: true,
      };

      if (includeFooter) {
        const noteFooter = `<<This note, in part generated by the AHS Jenkins Scribe, is approved for the medical record. Note ID: ${draftNote.tag}. The patient verbally consented to using this tool.>>`;

        draftNote.text += `\n\n${noteFooter}`;
      }

      onGenerated(draftNote);
    } catch (e: unknown) {
      onError(e as ApplicationError, () => generateNote(noteType, transcript));
    } finally {
      setGeneratingNoteType(undefined);
    }
  };

  const abort = () => {
    controller.abort();
    setGeneratingNoteType(undefined);
  };

  return { generateNote, abort, generatingNoteType } as const;
}
