"use client";

import { useEffect } from "react";
import { Button } from "@nextui-org/button";
import {
  Modal,
  ModalBody,
  ModalContent,
  ModalFooter,
  ModalHeader,
  useDisclosure,
} from "@nextui-org/modal";
import { Divider } from "@nextui-org/divider";
import { ScrollShadow } from "@nextui-org/scroll-shadow";

export const TermsOfUse = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();

  useEffect(() => {
    let termsAgreed: string | null = sessionStorage.getItem("termsAgreed");

    if (!termsAgreed || termsAgreed !== "Yes") {
      onOpen();
    }
  }, []);

  const handleAgreed = () => {
    sessionStorage.setItem("termsAgreed", "Yes");
    onClose();
  };

  return (
    <Modal
      backdrop="blur"
      hideCloseButton={true}
      isDismissable={false}
      isKeyboardDismissDisabled={false}
      isOpen={isOpen}
      placement="center"
      scrollBehavior="inside"
      size="lg"
    >
      <ModalContent>
        <ModalHeader>Terms of Use</ModalHeader>
        <ModalBody>
          <ScrollShadow>
            <div className="flex flex-col gap-6 justify-center items-center">
              <div className="flex flex-col gap-3 text-small text-zinc-500 max-w-[90%] sm:max-w-[600px]">
                <p className="text-red-500 font-semibold">
                  <strong>Important</strong> - AHS Jenkins Terms of Use (Updated
                  September 3, 2024)
                </p>
                <p>
                  By using the AI Scribe application, you agree to the following
                  terms:
                </p>
                <p className="ms-6">
                  <ul className="list-none list-inside space-y-2">
                    <li>
                      <strong>Patient Consent: </strong>You must obtain verbal
                      consent from each patient before the initial use on each
                      visit, adhering the approved consent script (shown below).
                    </li>
                    <li>
                      <strong>Data Sharing and Retention: </strong> Audio
                      recordings, transcripts, and summaries of patient
                      conversations will be shared with the project team for
                      Quality Improvement (QI) purposes. This data will be
                      retained for the duration of the project and will be
                      securely deleted upon the project&apos;s conclusion,{" "}
                      <em>unless you choose to delete it earlier</em>.
                    </li>
                    <li>
                      <strong>Content Integrity: </strong> When copy/pasting
                      content into a Connect Care note, please do not delete or
                      alter the note footer. The integrity of the footer must be
                      maintained to ensure proper attribution and
                      record-keeping. You may still edit the content of the note
                      as you see fit.
                    </li>
                    <li>
                      <strong>Recording Device Visibility: </strong> The
                      recording device (e.g., mobile device, laptop, wireless on
                      wheels workstation) must be clearly visible to the
                      patient.
                    </li>
                    <li>
                      <strong>Limitations of Use: </strong> The content
                      generated by the AI Scirbe, including transcripts and
                      summaries, is intended solely for documentation purposes.
                      It should not be used as a diagnostic tool or as a
                      substitute for clinical judgment.
                    </li>
                  </ul>
                </p>
                <p>
                  <strong>Consent Script:</strong>
                  <br />
                  &quot;I would like to use a transcription tool for our visit
                  today. It helps increase the time for direct patient care in
                  Alberta&apos;s Health Care System. I would like your
                  permission to record and transcribe your visit. I will use
                  this to help summarize the outcomes of your visit on your
                  chart. Saying no to being recorded is okay and will have no
                  impact on your care.&quot;
                </p>
              </div>
            </div>
          </ScrollShadow>
        </ModalBody>
        <ModalFooter className="flex flex-col gap-2 items-end">
          <Divider className="md:hidden" />
          <Button color="primary" onPress={handleAgreed}>
            I Agree
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};
