--!jinja

CREATE OR REPLACE SCHEMA JENKINS_DEV_{{SCHEMA_SUFFIX}};
USE SCHEMA JENKINS_DEV_{{SCHEMA_SUFFIX}};

EXECUTE IMMEDIATE FROM './CreateAppTables.sql';
EXECUTE IMMEDIATE FROM './UpdateBuiltinNoteDefinitions.sql';
